version: '3.9'
services:
  backend:
    container_name: golang_container
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres:latest
    container_name: database_container
    build:
      context: ./database/
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - default
    
